# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eee1f92a34bf4789078a5e28b95254ee03bedd3ca5b9b68c5c7151ace38a20c8bc0566e8b548d7e07380de13b3567a09bd0f63fff874718490074737f5735d81

test:
  secret_key_base: ffad8162ca67ca8d913ab217c618d6294b28e5b77407189322640eac56b044c8eb5217324b148c7e67341ddfd9fe45432262e513bc35adde4dee0819c4c7c32d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
